# prompt_format: no_guide
# max_tokens: 128
# temperature: 0.0
# model: openai/gpt-4o-2024-08-06
# seed: 5768
# feature: stance
# bank: bank_negara_malaysia
# batch_size: 1
prompt_format: no_guide
max_tokens: 128
temperature: 0.0
# model: openai/gpt-4o-2024-08-06
model: gemini/gemini-2.0-flash
seed: 78516
# seed: 5768
# feature: certain
feature: certain
bank: swiss_national_bank
# bank: bank_negara_malaysia
batch: 1
