# prompt_format: no_guide
# max_tokens: 128
# temperature: 0.0
# model: openai/gpt-4o-2024-08-06
# seed: 5768
# feature: stance
# bank: bank_negara_malaysia
# batch_size: 1
prompt_format: no_guide
max_tokens: 128
temperature: 0.0
# model: openai/gpt-4o-2024-08-06
model: together_ai/meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
seed: 944601
# seed: 5768
# feature: certain
feature: certain
bank: bank_of_korea
# bank: bank_negara_malaysia
batch: 5
