# prompt_format: no_guide
# max_tokens: 128
# temperature: 0.0
# model: openai/gpt-4o-2024-08-06
# seed: 5768
# feature: stance
# bank: bank_negara_malaysia
# batch_size: 1
prompt_format: no_guide
max_tokens: 128
temperature: 0.0
# model: openai/gpt-4o-2024-08-06
model: together_ai/meta-llama/Llama-4-Scout-17B-16E-Instruct
seed: 5768
# seed: 5768
# feature: certain
feature: time
bank: bank_of_korea
# bank: bank_negara_malaysia
batch: 5
