# prompt_format: no_guide
# max_tokens: 128
# temperature: 0.0
# model: openai/gpt-4o-2024-08-06
# seed: 5768
# feature: stance
# bank: bank_negara_malaysia
# batch_size: 1
prompt_format: no_guide
max_tokens: 128
temperature: 0.0
# model: openai/gpt-4o-2024-08-06
model: together_ai/Qwen/Qwen2.5-72B-Instruct-Turbo
seed: 78516
# seed: 5768
# feature: certain
feature: stance
bank: central_bank_of_china_taiwan
# bank: bank_negara_malaysia
batch: 1
