# prompt_format: no_guide
# max_tokens: 128
# temperature: 0.0
# model: openai/gpt-4o-2024-08-06
# seed: 5768
# feature: stance
# bank: bank_negara_malaysia
# batch_size: 1
prompt_format: no_guide
max_tokens: 128
temperature: 0.0
# model: openai/gpt-4o-2024-08-06
model: openai/gpt-4.1-mini-2025-04-14
seed: 5768
# seed: 5768
# feature: certain
feature: certain
bank: monetary_authority_of_singapore
# bank: bank_negara_malaysia
batch: 2
