# prompt_format: no_guide
# max_tokens: 128
# temperature: 0.0
# model: openai/gpt-4o-2024-08-06
# seed: 5768
# feature: stance
# bank: bank_negara_malaysia
# batch_size: 1
prompt_format: no_guide
max_tokens: 128
temperature: 0.0
model: openai/gpt-4o-2024-08-06
seed: 944601
# seed: 5768
feature: certain
bank: bank_of_canada
# bank: bank_negara_malaysia
batch: 1
